### PR TITLE
Feature/kas 3832 delete job

### PR DESCRIPTION
**Pull request by ValenberghsSven**
Draft to attempt to solve issue with physical zip being removed but metadata still existing, causing problems in the frontend.
Will elaborate on all changes later

### CODE REVIEW

**Comment by ValenberghsSven** [comment]
I added a query to check missing zips but I was thinking in metadata, not on disk file so query is pointless.
Idea :bulb: On service startup we could add a verify function for all jobs. Checking all generated files from all jobs once.
If the issue persists we could reboot the service to fix that instance of the issue.

**Comment by ValenberghsSven** [comment]
FYI this feature is currently deployed on ACC and PROD in override.yml

**Review by sergiofenoll — APPROVED** [review]
Ran it locally, does what it says on the tin, and the code looks good.

**Comment by ValenberghsSven** [comment]
on PROD no `socket hangup` has occured since deploying this branch.
After 2 weeks, restarting the service listed that all archives had files on disk, so no files have gone missing since.
Will bump

**Pull request merged**
